

// USER ADD
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name":"yücel",
    "surname":"akgül",
    "email":"yücel@gmail.com",
    "phone":"05538080143",
    "country":"türkiye",
    "gender":"erkek",
    "address":"mahmudiye mah 303"
}




###
// UPDATE USER FOR İD
PATCH http://localhost:3000/api/users/642de10dee9b0624c4f8bdb5
Content-Type: application/json
 
{
    "name":"oguz3",
    "surname":"ekin3",
    "email":"oguz3@gmail.com",
    "phone":"05539191773",
    "country":"almanya",
    "gender":"erkek",
    "address":"mahmudiye mah 303"
    
}

###
// login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "phone":"05538080143"
}

###
//delete
DELETE  http://localhost:3000/api/users/642de10dee9b0624c4f8bdb5
Content-Type: application/json
//silme işlemi
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDJkZTEwZGVlOWIwNjI0YzRmOGJkYjUiLCJpYXQiOjE2ODA3Mjk3NzQsImV4cCI6MTY4MDczMzM3NH0.x7VybN6QjjLu6aWfjV1uf2PnWcsdqEzX6ZLaa-m0a9s


###
//admin update with user
PATCH http://localhost:3000/api/users/me
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDJkZTEwZGVlOWIwNjI0YzRmOGJkYjUiLCJpYXQiOjE2ODA3Mjk2MzcsImV4cCI6MTY4MDczMzIzN30.PssMiNo_94v9rcNtXUSh_SRBbEcLUnC7YDeoqVESTbs
 
{
    "name":"rootdeneme",
    "surname":"rootdeneme"
}


###
// admin control
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDJkZTBmM2VlOWIwNjI0YzRmOGJkYjQiLCJpYXQiOjE2ODA3Mjk4MzksImV4cCI6MTY4MDczMzQzOX0.WZwQZ5Ru7E0OZHLKN3maeSoykY97hcInBMGQp2mkSVs
// token ile admin kontrolü,eğer verilen token admin ise diğer kullanıcılaro gçrebilir değil ise göremez